name: Markdown Lint

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  markdown-lint:
    name: Check Markdown Files
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install -g glob chalk
        
    - name: Check markdown trailing newlines
      run: |
        echo "🔍 Checking markdown files for proper trailing newlines..."
        node scripts/fix-markdown-trailing-newlines.js --check
        
    - name: Run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@v11
      with:
        config: '.markdownlint.json'
        globs: |
          **/*.md
          !node_modules
          !dist
          !build
        
    # Optional: Auto-fix and commit (only on push to main)
    - name: Auto-fix markdown issues
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && failure()
      run: |
        echo "🔧 Auto-fixing markdown issues..."
        node scripts/fix-markdown-trailing-newlines.js
        
    - name: Commit fixes
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && failure()
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'fix: Auto-fix markdown trailing newlines [skip ci]'
        file_pattern: '*.md'
        commit_user_name: 'github-actions[bot]'
        commit_user_email: 'github-actions[bot]@users.noreply.github.com'